---
- hosts: leaders
  sudo: True

  pre_tasks:
    - name: Update APT cache
      apt: update_cache=yes

  roles:
    - { role: "geotrellis-spark-cluster.common" }
    - { role: "azavea.pptpd", when: "['packer'] | is_in(group_names)" }
    - { role: "geotrellis-spark-cluster.graphite" } 
    - { role: "geotrellis-spark-cluster.grafana" }
    - { role: "azavea.statsite" }
    - { role: "geotrellis-spark-cluster.hdfs", hdfs_namenode: True }
    - { role: "geotrellis-spark-cluster.mesos", mesos_leader: True }
    - { role: "geotrellis-spark-cluster.accumulo", accumulo_leader: True }
    - { role: "geotrellis-spark-cluster.cleanup" }
